name: deploy-website
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-website.yml
      - website/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@db6bcf6eb8d88a8aa03265b887ec7bd84d64cd68 # v2.1.1
        with:
          bun-version-file: package.json
          no-cache: true
      - run: bun ci
      - run: bun run build
      - uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2.0.7
        id: create-deployment
        with:
          token: ${{ github.token }}
          environment: production
          production-environment: true
      - run: bun wrangler deploy --no-bundle
        id: deploy
        working-directory: website
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          WRANGLER_SEND_METRICS: false
      - uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        if: success()
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
          environment-url: https://filtron.dev
          state: success
      - uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        if: failure()
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
          state: failure
