name: lint
on:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -Ls "https://github.com/rhysd/actionlint/releases/download/v${{ env.version }}/actionlint_${{ env.version }}_linux_amd64.tar.gz" | sudo tar -x -z -C /usr/local/bin actionlint
        env:
          version: "1.7.8"
      - run: |
          echo "::add-matcher::.github/matchers/actionlint.json"
          actionlint -color

  vale:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -Ls "https://github.com/errata-ai/vale/releases/download/v${{ env.version }}/vale_${{ env.version }}_Linux_64-bit.tar.gz" | sudo tar -x -z -C /usr/local/bin vale
        env:
          version: "3.13.0"
      - run: |
        echo "::add-matcher::.github/matchers/vale.json"
        find . -type f -name "*.md" -not -path "*/.github/*" -not -path "*/node_modules/*" | xargs vale 

  validate-renovate-config:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files: .github/renovate.json
      - uses: oven-sh/setup-bun@v2
        if: steps.changed-files.outputs.any_changed == 'true'
      - run: bun install -g renovate
        if: steps.changed-files.outputs.any_changed == 'true'
      - run: renovate-config-validator .github/renovate.json
        if: steps.changed-files.outputs.any_changed == 'true'

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - run: bun install
      - run: bun oxlint --type-aware

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - run: bun install
      - run: bun oxfmt --check
