name: preview-website
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - website/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    outputs:
      deployment-url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
        with:
          bun-version-file: package.json
          no-cache: true
      - run: bun ci
      - run: bun run build
        working-directory: website
      - uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2.0.7
        id: create-deployment
        with:
          token: ${{ github.token }}
          environment: pr-${{ github.event.pull_request.number }}
          transient-environment: true
          production-environment: false
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: website
          command: deploy --project-name=filtron --env=pr-${{ github.event.pull_request.number }}
      - uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
          environment-url: ${{ steps.deploy.outputs.deployment-url }}
          state: success

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: website
          command: delete --project-name=filtron --env=pr-${{ github.event.pull_request.number }} --yes
      - uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3
        with:
          token: ${{ github.token }}
          environment: pr-${{ github.event.pull_request.number }}
