name: publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.verify.outputs.packages }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: package.json
          no-cache: true
      - run: |
          tags=$(git tag --points-at HEAD)
          if [ -z "$tags" ]; then
            echo "Error: No tags found pointing at HEAD"
            exit 1
          fi
          echo "$tags" | xargs bun run scripts/verify-tag.ts
        id: verify

  publish:
    runs-on: ubuntu-24.04
    needs: verify
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        package: ${{ fromJson(needs.verify.outputs.packages) }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: package.json
          no-cache: true
      - run: bun ci
      - run: |
          cd "${{ matrix.package.dir }}"
          bun run build
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd "${{ matrix.package.dir }}"
          npm publish --provenance --access public
