name: test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: package.json
      - run: bun ci
      - run: bun run build
      - run: bun test --reporter=junit --reporter-outfile=junit.xml --coverage --coverage-reporter=lcov --coverage-dir=coverage
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        if: ${{ !cancelled() }}
        with:
          use_oidc: true
          files: ./coverage/lcov.info
          disable_search: true
      - uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        if: ${{ !cancelled() }}
        with:
          use_oidc: true
          file: ./junit.xml
          disable_search: true

  e2e:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - setup: node
            version: "20"
            test_cmd: node -e
          - setup: node
            version: "22"
            test_cmd: node -e
          - setup: node
            version: "24"
            test_cmd: node -e
          - setup: bun
            version: "1.1"
            test_cmd: bun -e
          - setup: bun
            version: "1.2"
            test_cmd: bun -e
          - setup: bun
            version: "1.3"
            test_cmd: bun -e
          - setup: deno
            version: "2.5.x"
            test_cmd: deno eval
    name: e2e (${{ matrix.setup }} ${{ matrix.version }})
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Bun (for building)
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: package.json

      - run: bun ci
      - run: bun run build

      - if: matrix.setup == 'node'
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: ${{ matrix.version }}

      - if: matrix.setup == 'bun'
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: ${{ matrix.version }}

      - if: matrix.setup == 'deno'
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.version }}

      - run: ${{ matrix.test_cmd }} "Promise.all([import('./packages/core/dist/index.js'), import('./packages/sql/dist/index.js')]).then(([core, sql]) => { const ast = core.parseOrThrow('age>18'); console.log(sql.toSQL(ast)); })"
